config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'welcome/index'

  resources :photos do
    resources :comments
  end

  root 'welcome#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :photo
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :photos
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  # Make users login before they can go anywhere on site
  before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  before_action :set_user

  def new
  end

  def create
    @photo = Photo.find(params[:photo_id])
    @comment = @photo.comments.build(comment_params)
    @comment.user = @user
    if @comment.save
      redirect_to @photo
    else
      render @photo
    end
  end

  private
  
  def set_user
    @user = current_user
  end

  def comment_params
    params.require(:comment).permit(:body)
  end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_user
  before_action :find_photo, only: [:update, :destroy]
  
  def index
    @photos = @user.photos
    @public_photos = Photo.where(:public => true)
  end

  def new
    @photo = Photo.new
  end

  def create
    @photo = Photo.new(photo_params)
    @photo.user = @user
    if @photo.save
      redirect_to @photo
    else
      render 'new'
    end
  end

  def show
    @photo = Photo.find(params[:id])
    @comment = Comment.new(:photo => @photo)
    if @photo.public || @photo.user == @user
      render 'show'
    else
      flash[:notice] = 'That photo is private!'
      redirect_to photos_path
    end
  end

  def edit
    @photo = Photo.find(params[:id])
    if @photo.public || @photo.user == @user
     render 'edit'
    else
     flash[:notice] = 'That photo is private!'
     redirect_to photos_path
    end
  end

  def update
    if @photo.update(photo_params)
      redirect_to @photo
    else
      render 'edit'
    end
  end

  def destroy
    @photo.destroy
    redirect_to photos_path
  end

  private

  def photo_params
    params.require(:photo).permit(:title, :url, :body, :public)
  end

  def find_photo
    @photo = @user.photos.find(params[:id])
  end

  def set_user
    @user = current_user
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_comment.html.erb
<p><strong><%= comment.user.email %></strong>: <%= comment.body %></p>

app/views/comments/_form.html.erb
<%= simple_form_for [@photo, @comment] do |f| %>
	<%= f.input :body %>
	<%= f.submit %>
<% end %>

app/views/layouts/_nav.html.erb
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>

app/views/layouts/_notice.html.erb
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Brugram</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/nav' %>

<%= render 'layouts/notice' %>

<%= yield %>

</body>
</html>

app/views/photos/_back.html.erb
<p><button onclick="goBack()">Back</button></p>

app/views/photos/_form.html.erb
<%= simple_form_for @photo do |f| %>
	<%= f.input :title %>
	<%= f.input :url %>
	<%= f.input :body %>
	<%= f.input :public %>

	<%= f.submit %>
<% end %>

app/views/photos/edit.html.erb
<h1>Edit: <%= @photo.title %></h1>

<%= render 'form' %>

app/views/photos/index.html.erb
<h1>List of photos</h1>
<ul>
<% @photos.each do |photo| %>
	<li><%= link_to photo.title, photo_path(photo) %></li>
<% end %>
</ul>
<h3>Other user's public photos</h3>
<ul>
<% @public_photos.each do |photo| %>
	<% if photo.user != current_user %>
	<li><%= link_to photo.title, photo_path(photo) %></li>
	<% end %>
<% end %>
</ul>

<%= render 'back' %>

app/views/photos/new.html.erb
<h1>Add a new photo</h1>

<%= render 'form' %>

<%= render 'back' %>

app/views/photos/show.html.erb
<h1><%= @photo.title %></h1>
<p><%= @photo.body %></p>
<%= image_tag @photo.url, :class => 'photos' %>
<% if @photo.user == @user %>
<p><%= link_to 'Edit', edit_photo_path(@photo) %> | <%= link_to 'Destroy', photo_path(@photo),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></p>
<% end %>
<% if @photo.comments.count > 0 %>
	<%= render @photo.comments.reverse %>
<% end %>
<%= render 'comments/form' %>
<%= render 'back' %>

app/views/welcome/index.html.erb
<h1>Welcome to Brugram</h1>
<p><%= link_to 'View your photos', photos_path %></p>
<p><%= link_to 'Add new photo', new_photo_path %></p>